### ISSUE TITLE
How to hide/remove plus button in header?

### ISSUE THREAD

**Issue by pawansn** [908Inc/stkiOS#12]
How to hide/remove plus button in header?

**Comment by dehimb** [comment]
Hi. Currently, this SDK is not supported.
You can check the source code for an ability to hide this button. If this not implemented - fork and implement all you need

**Comment by pawansn** [comment]
"You can check the source code for an ability to hide this button" 
But I can't find a code to hide + button...

**Comment by pawansn** [comment]
Hey @dehimb please tell us that how to remove/hide?


![screen shot 2018-05-23 at 12 08 38 pm](https://user-images.githubusercontent.com/39483677/40407527-5c501d20-5e82-11e8-9918-01c38d5516c5.png)
