### ISSUE TITLE
Could not load NIB in bundle ResBundle.bundle

### ISSUE THREAD

**Issue by omarchaabouni** [908Inc/stkiOS#5]
When I try to run the sample on an iphone, it works well. However when I try to run it on an iPad I get an exception : 
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/7FBE2145-BB62-4D7C-AF4F-26140162DF2F/Edukily.app/ResBundle.bundle> (not yet loaded)' with name 'STKStickersView''

**Comment by Hatko** [comment]
Hello, SDK is updated, problem should be fixed
