### ISSUE TITLE
Crashes on addStickersObject line in STKStickerPack+CoreDataClass.m

### ISSUE THREAD

**Issue by DeepakMaheshwari05** [908Inc/stkiOS#6]
Hi, I am getting a crash on 
`[self addStickersObject: sticker];`

The log from Xcode is : 

> 2017-05-16 15:37:57.116 NudgeBuddies[403:63023] WARNING: GoogleAnalytics 3.17 void GAIUncaughtExceptionHandler(NSException *) (GAIUncaughtExceptionHandler.m:48): Uncaught exception: *** -[NSSet intersectsSet:]: set argument is not an NSSet
> 2017-05-16 15:38:02.164 NudgeBuddies[403:63023] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSSet intersectsSet:]: set argument is not an NSSet'
> *** First throw call stack:
> (0x18191d900 0x180f8bf80 0x181876a38 0x18226d148 0x182207a74 0x18226d030 0x1834151cc 0x10004c668 0x18190faa8 0x10004c52c 0x1001097ac 0x1000c1004 0x10007fa80 0x1001470e4 0x102101bf0 0x102101bb0 0x102107658 0x1818d4bb0 0x1818d2a18 0x181801680 0x182d10088 0x186678d90 0x1001bbb98 0x1813a28b8)
> libc++abi.dylib: terminating with uncaught exception of type NSException
>

**Comment by Hatko** [comment]
Hello,

could you please clarify - what version of StickerPipe do you use?

**Comment by DeepakMaheshwari05** [comment]
Hi,
I am using ver 0.4.0

**Comment by Hatko** [comment]
You can update it to 0.4.3, current version, the problem should be fixed

**Comment by DeepakMaheshwari05** [comment]
Hi,
Actually, I am not using Cocoa pods.I am integrating the stickerpipe SDK manually to the app, so from where I get the current version.

**Comment by Hatko** [comment]
Got it.

In this case, you can clone it from 
https://github.com/908Inc/stkiOS/tree/master/SDK

**Comment by DeepakMaheshwari05** [comment]
Hi, I have updated the SDK but the problem exists and the problem is coming on some devices not all.

**Comment by Hatko** [comment]
Hm, it is really strange, because code firing this error message 

`[self addStickersObject: sticker];`

doesn't exist in current SDK. Do you call it manually?

If so, you should call 

`[self addStickerObjectFixed:sticker];`

instead. It's a known bug of CoreData, existed in iOS 9

**Comment by Hatko** [comment]
@DeepakMaheshwari05, can this be closed? Have you managed to solve an issue?

**Comment by DeepakMaheshwari05** [comment]
Yes, it resolved.
