### ISSUE TITLE
How can I remove some Preinstalled Stickers packs ?

### ISSUE THREAD

**Issue by gbr33** [908Inc/stkiOS#9]
Hi
I integrate your SDK with QuickBlox/q-municate-ios and it's all works fine but I wonder if I can remove some Preinstalled Stickers packs and keep my won stickers packs only ?
Thanks a lot.

**Comment by dehimb** [comment]
Hi @gbr33 
You can provide your stickerpipe client(email) and we can disable preinstalled packs for you
You can contact me with email cto@stickerpipe.com
